### ISSUE TITLE
Ensure mode type definition has allowed values

### ISSUE THREAD

**Issue by brylie** [maasglobal/maas-tsp-api#22]
In the OpenAPI Designer UI, the 'mode' type definition seems to have some allowed values listed. However, the allowed values are not being displayed.

# Task
- [ ] Determine why the allowed values are not displaying.
- [ ] If necessary, update the 'mode' definition allowed values so they display correctly

**Comment by huksley** [comment]
As the schemas now are part of [maas-schemas](https://github.com/maasglobal/maas-schemas/) project I am mass closing all old issues related to type definitions.
