### ISSUE TITLE
UI difference on Android and IOS

### ISSUE THREAD

**Issue by Pumpulina** [maasglobal/maas-tsp-api#38]
Text difference IOS: "Your real name is needed for identification purposes when making bookings or issuing tickets" 
Android (app version 1.5.241): also not allowing date of birth entry 
![android](https://user-images.githubusercontent.com/29072250/52426959-b6042080-2b07-11e9-8dcc-4c1c479422ee.PNG)

**Comment by huksley** [comment]
Hi,

Thank for the good feedback. This is forwarded to our product development.

I will close this issue because we will not be able to provide a follow up on this issue here.
