### ISSUE TITLE
Link to provider terms

### ISSUE THREAD

**Issue by loleg** [maasglobal/maas-tsp-api#42]
After installing the production Android app and activating the Whim Urban 30 plan for Helsinki, the user is asked to enter data into the HSL website. However, this externally hosted form provides no details about how the data is collected. It is unclear whether the Whim terms apply. I suggest adding a link above the button to the provider policy. Screenshot attached.

![Screenshot_20191119-203058](https://user-images.githubusercontent.com/31819/69218628-ca3a7b00-0b79-11ea-86dd-47daac765196.png)

**Comment by huksley** [comment]
Hi, 

Thank for the good feedback. This is forwarded to our product development.

I will close this issue because we will not be able to provide a follow up on this issue here.
